name: Deploy to Github Pages
on:
    push:
        branches:
            - development

jobs:
    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Create Node Environment
              uses: actions/setup-node@v1
              with: 
                node-version: 16.x
            - name: Cache node modules
              id: cache-nodemodules
              uses: actions/cache@v2
              env:
                cache-name: cache-node-modules
              with:
                # caching node_modules
                path: node_modules
                key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
                restore-keys: |
                  ${{ runner.os }}-build-${{ env.cache-name }}-
                  ${{ runner.os }}-build-
                  ${{ runner.os }}-    
            - name: Install Packages and Build Application
              if: steps.cache-nodemodules.outputs.cache-hit != 'true'
              run: |
                npm install -g @vue/cli yarn
                yarn install
            - name: Build Application
              run: | 
                yarn build
            - name: Run linter
              run: |
                yarn lint
            - name: Run unit test cases
              run: |
                yarn test:unit
            # - name: Run e2e test cases
            #   run: |
            #     yarn cy:run
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                REPO: self
                BRANCH: production
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BASE_URL: https://api.tvmaze.com
